// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATHrHfqEVSzssb4kjZrX95LvouskHfQ4E',
    appId: '1:375006835997:web:651040e66e099ecabcddf4',
    messagingSenderId: '375006835997',
    projectId: 'duitkita-8451b',
    authDomain: 'duitkita-8451b.firebaseapp.com',
    storageBucket: 'duitkita-8451b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuYIG_mehkLuSgB94t3tTAfkYCF8BVuKI',
    appId: '1:375006835997:android:59729b01273585c4bcddf4',
    messagingSenderId: '375006835997',
    projectId: 'duitkita-8451b',
    storageBucket: 'duitkita-8451b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiG-VSz5mlSC128KvIxg4ZGNoYVeMNED8',
    appId: '1:375006835997:ios:69003a93119d9640bcddf4',
    messagingSenderId: '375006835997',
    projectId: 'duitkita-8451b',
    storageBucket: 'duitkita-8451b.firebasestorage.app',
    iosBundleId: 'com.example.duitkita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiG-VSz5mlSC128KvIxg4ZGNoYVeMNED8',
    appId: '1:375006835997:ios:69003a93119d9640bcddf4',
    messagingSenderId: '375006835997',
    projectId: 'duitkita-8451b',
    storageBucket: 'duitkita-8451b.firebasestorage.app',
    iosBundleId: 'com.example.duitkita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATHrHfqEVSzssb4kjZrX95LvouskHfQ4E',
    appId: '1:375006835997:web:19b32aab461f0574bcddf4',
    messagingSenderId: '375006835997',
    projectId: 'duitkita-8451b',
    authDomain: 'duitkita-8451b.firebaseapp.com',
    storageBucket: 'duitkita-8451b.firebasestorage.app',
  );
}
